### ISSUE TITLE
package rocks.heikoseeberger.akkounts.grpc does not exist

### ISSUE THREAD

**Issue by YikSanChan** [hseeberger/akkounts#1]
While it is imported by https://github.com/hseeberger/akkounts/blob/522cb6a3db9f1efce7d7a87235cd66e97c66c867/src/main/scala/rocks/heikoseeberger/akkounts/AkkountsServiceImpl.scala#L20

**Comment by hseeberger** [comment]
These classes are generated from Protocol Buffers definitions by the sbt build. Have you run `sbt compile`? This should generate these Scala files unter `target/scala_2.13/src_managed/...`.
